import './globals.css'
import {Header} from "@/app/projects/Header";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={'min-h-screen'}>
      <Header/>
      {children}
      </body>
    </html>
  )
}
